import { useQueryClient } from "@tanstack/react-query"
import { 
  useGetMe, 
  useLogout,
  useListRepos, 
  useCreateRepo, 
  useListWorkspaces,
  useOpenWorkspace,
  useGetWorkspace,
  useCloseWorkspace,
  useGetWorkspaceStats,
  useListFiles,
  useReadFile,
  useWriteFile,
  useGetDiff,
  useListBranches,
  useSwitchBranch,
  useCommitChanges,
  useListMessages,
  useSendMessage,
  getListReposQueryKey,
  getListWorkspacesQueryKey,
  getGetWorkspaceQueryKey,
  getGetWorkspaceStatsQueryKey,
  getListFilesQueryKey,
  getGetDiffQueryKey,
  getListBranchesQueryKey,
  getListMessagesQueryKey
} from "@workspace/api-client-react"

export {
  useGetMe,
  useLogout,
  useListRepos,
  useCreateRepo,
  useListWorkspaces,
  useOpenWorkspace,
  useGetWorkspace,
  useCloseWorkspace,
  useGetWorkspaceStats,
  useListFiles,
  useReadFile,
  useWriteFile,
  useGetDiff,
  useListBranches,
  useSwitchBranch,
  useCommitChanges,
  useListMessages,
  useSendMessage,
  getListReposQueryKey,
  getListWorkspacesQueryKey,
  getGetWorkspaceQueryKey,
  getGetWorkspaceStatsQueryKey,
  getListFilesQueryKey,
  getGetDiffQueryKey,
  getListBranchesQueryKey,
  getListMessagesQueryKey
}
